language: objective-c
osx_image: xcode8
cache:
  - bundler

before_install:
- make install_bundle carthage_extract

script:
- make lint test

after_script:
  - bash <(curl -s https://codecov.io/bash)
