language: objective-c
osx_image: xcode8
cache:
  - bundler

before_install:
- brew install git-lfs
- git lfs install
- git lfs pull
- make install_bundle carthage_extract

script:
- make test

after_script:
  - bash <(curl -s https://codecov.io/bash)
