version: '2'
volumes:
  pacts:
services:
  pact_broker:
    image: rajatvig/pactbroker:0.1.3
    hostname: broker
    domainname: docker.local
    environment:
      PACT_BROKER_DATABASE_USERNAME: pactbroker
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: db.docker.local
      PACT_BROKER_DATABASE_NAME: pactbroker
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db:db.docker.local
  db:
    image: postgres
    hostname: db
    domainname: docker.local
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: pactbroker
      POSTGRES_DB: pactbroker
    ports:
      - "5432:5432"
  pactbroker_client:
    image: rajatvig/pactbroker-client:0.1.1
    environment:
      CONSUMER_VERSION: 0.1.0
      URI_BROKER: http://broker.docker.local
    volumes:
      - ./pacts:/pacts
    depends_on:
      - pact_broker
    links:
      - pact_broker:broker.docker.local
  pact_broker_proxy:
    image: dius/pact-provider-verifier-docker
    hostname: proxy
    domainname: docker.local
    environment:
      pact_urls: http://broker.docker.local/pacts/provider/TodoBackendService/consumer/TodoiOSClient/latest
      provider_base_url: http://10.37.129.2:3000
      provider_states_url: http://10.37.129.2:3000/states
      provider_states_active_url: http://10.37.129.2:3000/states/active
    depends_on:
      - pact_broker
    links:
      - pact_broker:broker.docker.local
